wiki: Add show / cat command
Signed-off-by: Lukas Czerner <lczerner@redhat.com>

diff --git a/wiki b/wiki
--- a/wiki
+++ b/wiki
@@ -30,6 +30,8 @@ usage()
 	edit <filename>		- edit a wiki file
 	rm <filename>		- remove a wiki file
 	list			- list all wiki files
+	append <filename>	- append line to the file
+	show <filename>		- cat the filename
 	<search terms>		- search for specified terms"
 }
 
@@ -183,6 +185,21 @@ do_append()
 	git_add $filename
 }
 
+do_show()
+{
+	if [ $# -gt 2 ]; then
+		echo "Error: too many arguments"
+		usage
+		exit 1
+	fi
+	filename=$2
+	if [ ! -f ${DATA_DIR}/$filename ]; then
+		echo "\"$filename\" does not exist!"
+		exit 1
+	fi
+	cat ${DATA_DIR}/$filename
+}
+
 search()
 {
 	if [ $# -lt 1 ]; then
@@ -225,6 +242,7 @@ case $CMD in
 	edit)		edit $@;;
 	list)		list $@;;
 	append)		do_append $@;;
+	show|cat)	do_show $@;;
 	rm | remove)	remove $@;;
 esac
 
@@ -232,7 +250,7 @@ case $CMD in
 	new|edit|rm|remove|add|append)
 		git_push
 		exit 0;;
-	list)
+	list|show|cat)
 		exit 0;;
 esac
 
